# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sample-InAppCallStatusBar' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Sample-InAppCallStatusBar
  # pod 'ASInAppCallStatusBar'
  
  pod 'ASInAppCallStatusBar', :path => '../'
  target 'Sample-InAppCallStatusBarTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Sample-InAppCallStatusBarUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
